### ISSUE TITLE
Can't install on ARM system

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost-Apps/gotosocial_ynh#1]
Due to the [actual helper](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_detect_arch/ynh_detect_arch__2) for detecting the system architecture, which does not differentiate armv6 and armv7 (only arm) and because gotosocial provides different binaries for those 2 architectures, this package cannot be installed on armv6 or armv7 architectures

**Comment by Tagadda** [comment]
Since YunoHost 4.3.1.8, you can the the `$YNH_ARCH` env variable (which is basically the return of `dpkg --print-architecture`), but I don't know if this command differentiate between armv6 and armv7 either...

**Comment by OniriCorpe** [comment]
my armv6 raspi zero w returns:
```
# dpkg --print-architecture
armhf
```

but idk too :")

**Comment by OniriCorpe** [comment]
with `uname -m` : 
my armv6 raspi zero w returns `armv6l`
and a friend's armv7 computer returns  `armv7l`

The [`$YNH_ARCH` ynh helper](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_detect_arch/ynh_detect_arch__2) seems using `uname -m`, so maybe we can just slightly edit it to differentiate those 2 arm variants?
`$YNH_ARCH` already distinguishes `arm64` from `arm` so I see no reason not to do so for these variants as well

**Comment by Tagadda** [comment]
`$YNH_ARCH` is using `dpkg --print-architecture`, but again I don't know if that differentiate armv6 and armv7 :/
https://github.com/YunoHost/yunohost/blob/93ed8efb1783be8b5fb49deb1acb2ffb790ba36a/src/app.py#L2330

**Comment by OniriCorpe** [comment]
> I don't know if that differentiate armv6 and armv7 :/

unfortunately no, it `dpkg --print-architecture` returns `armhf` for both :/

**Comment by Tagadda** [comment]
I think you can tweak `ynh_detect_arch` to differentiate those arch and put it in `_common.sh` to use it in all your scripts
