### ISSUE TITLE
Implement OpenID Connect (OIDC)

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost-Apps/gotosocial_ynh#23]
GTS supports OIDC, so it would be nice to allow YNH accounts to connect to GTS through this, with the help of [dex_ynh](https://github.com/Yunohost-Apps/dex_ynh) (or maybe [canaille](https://gitlab.com/yaal/canaille/))

docs: https://docs.gotosocial.org/en/latest/configuration/oidc/

**Comment by PrivacyDragon** [comment]
This is by now already possible, right?
(I have set up Dex for OIDC. And that works. Though I have to manually edit the config file of GTS every time after an update.)

**Comment by OniriCorpe** [comment]
hi @PrivacyDragon and thanks for the reminder about OIDC

can you provide me with a valid configuration example to help me implement this appropriately?

**Comment by PrivacyDragon** [comment]
You mean configuration on the GoToSocial side, I guess?
That is really just in the configuration example.
So, I set `oidc-enabled` to `true`
And then `oidc-idp-name` to `Dex`
I kept the `oidc-skip-verification` at `false`. The comment above it states that it should never be set to true in production.
I set `oidc-client-id` to what I set as appname to be used with Dex. (So, "GoToSocial", in this case.)
for `oidc-client-secret` I had DuckDuckGo generate a random UUID, which I had to set in Dex as the client-secret as well.
I kept `oidc-scopes` at the default.
I think the official documentation gives a proper example?
https://docs.gotosocial.org/en/latest/configuration/oidc/

**Comment by OniriCorpe** [comment]
@PrivacyDragon have you been able to test OIDC with the implementation that has been made?
Everything okay? I had tested it myself, but I ask you

**Comment by PrivacyDragon** [comment]
Yes, I can confirm that it seems to be okay.
(Though comparing it to how I always edited it by hand, there is one difference. It looks like you put an extra blank space after 'oidc-enabled:'. So instead of `oidc-enabled: true` you have it `oidc-enabled:  true`.
However, that is not important for the config to work. It works. More of a cleanliness thing.)

**Comment by OniriCorpe** [comment]
> It looks like you put an extra blank space

It seems to be a core config panel bug, because I've checked everything and I can't find anything in my code that would do that :/
