### ISSUE TITLE
Unexpected token < on JSON

### ISSUE THREAD

**Issue by xmgz** [YunoHost-Apps/gotosocial_ynh#33]
### Describe the bug

some changes on web admin panel are not saved.

### Context

- Hardware:  Raspberry Pi 
- YunoHost version: 463 latest stable
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- latest 0.3.6 gotosocial

### Steps to reproduce

* log in as admin in /admin panel
* edit "description" field (actually any, as I've tried with "short description" an "email" fields)
* click save button
* changes are not saved and I get this info

![issue's screenshot](https://i.imgur.com/xn6Icdu.png "screenshot")

### Expected behavior

changes are saved to config.yaml (or where changes belong)

### Logs

I don't see anything about this issue in /var/log/gotosocial/gotosocial.log

I could upload a blocked instances list though.

Many thanks

**Comment by OniriCorpe** [comment]
hi!

I doubt that this bug comes from the ynh package :/

I recommend you to open an issue on the [upstream GTS repo](https://github.com/superseriousbusiness/gotosocial/issues)
