### ISSUE TITLE
Unclear duplicated fields in config panel

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/gotosocial_ynh#53]
### Describe the bug

The installation process fails

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.0.10.2
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- open the config panel in the admin section
- see this:
![Screenshot 2022-11-09 at 5 52 24 PM](https://user-images.githubusercontent.com/42862428/200892141-1ba58211-e73f-4e01-9998-699595996825.jpg)

### Expected behavior

There should be three different descriptions for three different values, but the same description is repeated three times.

**Comment by OniriCorpe** [comment]
well spotted!
it's fixed and will be deployed soon
