### ISSUE TITLE
fetching issues

### ISSUE THREAD

**Issue by lucyferu** [YunoHost-Apps/gotosocial_ynh#81]
### Describe the bug

i encountering fetching issues that dont seem to happen on gts server not installed thought ynh.
the issues are:

-     random post fetching issues (error 500)
-     inability to "steal" or upload custom emojis on my instance
-     other instance (and also some clients like phanpy) cannot fetch the avatar of the accounts on my instance

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.20
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.8.1~ynh1

### Steps to reproduce

try to fetch toots and/or accounts from links (with some it works) and/or try to add custom emojis in any of the available ways.

### Expected behavior

being able to fetch toots, accounts and add custom emoji.

### Logs

the [**log**](https://paste.yunohost.org/bivesujipo) is from a couple of weeks ago because it's when i reported it to gts and found out it must be a ynh issue.

**Comment by OniriCorpe** [comment]
hi!

for now, I've tested the emoji stealing feature, manual upload of emojis, and the avatar retrieval from a third-party instance, and all work fine

![a gotosocial user profile showed on mastodon, with visible avatar and header images](https://github.com/YunoHost-Apps/gotosocial_ynh/assets/6963387/f2a0c874-a9f8-4660-a625-3afefd9079e5)

![a screenshot of the emoji stealing feature when stealing emojis](https://github.com/YunoHost-Apps/gotosocial_ynh/assets/6963387/89cc1ebe-e2f4-4bb7-89a6-21240d69e234)
![3 stolen emojis](https://github.com/YunoHost-Apps/gotosocial_ynh/assets/6963387/7a591a69-6ad3-47f6-986d-06153c8d6394)

was another instance of any federated software (gotosocial, mastodon, pleroma, etc) on the **same** domain name before your current instance?
are you sure you are entering a link to a public (unrestricted) post to get emojis?

**Comment by lucyferu** [comment]
> was another instance of any federated software (gotosocial, mastodon, pleroma, etc) on the **same** domain name before your current instance?

i dont think so.
maybe, ive tried to install gts more than once?
but i feel i also believing this because im doubting my memory after the question. 🙃 



> are you sure you are entering a link to a public (unrestricted) post to get emojis?

i know i did that mistake, but ive tried public posts too.
also, sometimes i cant fetch entire people's account. open account, without follow request.



> and can you provide me with the link to the issue opened on the upstream repository?

it was just a question on the matrix channel.

**Comment by OniriCorpe** [comment]
if you install a fedi software, during the federation it will share authentication keys
and if you put another software on the exact same domain name (or sub-domain), the other servers that had federated with the other instance will refuse to federate with the new instance because the keys will not match

I don't know if this is the case for you, but it's a plausible hypothesis

in any case, I don't have enough knowledge to debug this :/
especially since I don't reproduce these errors at all with my 2 GTS instances (test and personal instances) hosted on my YNH server

can you update to version 0.9.0 which is now available and tell me if these problems are still there?

**Comment by lucyferu** [comment]
as soon as i updated all the emoji showed up! yayyyy!! 🥳 

no idea what happened, but everything seems fine now.

thank you very much for the support.
