### ISSUE TITLE
[question] is link to media broken?

### ISSUE THREAD

**Issue by xmgz** [YunoHost-Apps/gotosocial_ynh#86]
it looks like so:

`timestamp="26/05/2023 05:48:09.400" func=middleware.Logger.func1.1 level=INFO latency="338.203µs" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0" method=GET statusCode=404 path=/fileserver/01VHYNX1AAVTTWR567M7NBM6SS/attachment/original/01BGMYST9724MNPRBPRTHDET54.png clientIP=195.xxx.yyy.200 requestID=q2t64cccccccccccc00awrs8rg msg="Not Found: wrote 21B"`

it happens with all previouly published pictures

It does not load multimedia (pictures) posted by user in any recent post.

I've test publishing a new picture and it was published, but non of the previous pictures are shown.

`01BGMYST9724MNPRBPRTHDET54.png` is not in that directory

```
$ ls 01VHYNX1AAVTTWR567M7NBM6SS/attachment/original
01AZRBYWJ02GB6Q2Z3HZSCC41T.jpg  01PTB3DZJAVBWXEH3522PW49K5.jpg
```

Updated to 0.9 ynh-2 from 0.8.1

**Comment by xmgz** [comment]
wait, is it trying to always  load multimedia from the same folder?
```
timestamp="26/05/2023 06:04:06.349" func=middleware.Logger.func1.1 level=INFO latency="753.015µs" userAgent="Calckey/13.1.4.1 (https://social.anotherexternaluser.com)" method=GET statusCode=404 path=/fileserver/01VHYNX1AAVTTWR567M7NBM6SS/attachment/original/01QY1WD5JX8D8V6CPN9B1MAMVP.jpeg clientIP=51.ccc.xxx.79 requestID=sh772nm8040003nk83ag msg="Not Found: wrote 21B"
timestamp="26/05/2023 06:04:06.355" func=middleware.Logger.func1.1 level=INFO latency=4.567017ms userAgent="Calckey/13.1.4.1 (https://social.anotherexternaluser.com)" method=GET statusCode=404 path=/fileserver/01VHYNX1AAVTTWR567M7NBM6SS/attachment/original/01E96RTYXW96J1YPXFXK850VBF.jpeg clientIP=51.ccc.xxx.79 requestID=ss772nm804001svbh75g msg="Not Found: wrote 21B"
timestamp="26/05/2023 06:04:08.750" func=middleware.Logger.func1.1 level=INFO latency="395.906µs" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0" method=GET statusCode=404 path=/fileserver/01VHYNX1AAVTTWR567M7NBM6SS/attachment/original/0132217CZCM3VPX7P5P4AHZWWR.jpg clientIP=195.xxx.ccc.200 requestID=5nc72nm804001wyn06vg msg="Not Found: wrote 21B"
```

I was reading logs and two diferent requests were made and always trying to fetch from `01VHYNX1AAVTTWR567M7NBM6SS` folder


the third request is myself, but the first two are from a user from another server

**Comment by xmgz** [comment]
it's not a 0.9 problem :/

I've restored backup and lots of 404

timestamp="26/05/2023 08:45:34.612" func=middleware.Logger.func1.1 level=INFO latency=37.52829ms clientIP=195.xxx.yyy.201 userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0" method=GET statusCode=404 path=/fileserver/01HN5ZS98WN3RS7MBHTD5CDKFQ/attachment/original/019X8PNN36Z7VW1BZ5TYRGCPNR.jpg requestID=dwhganw8040008d2q9pg msg="Not Found: wrote 1.96kiB"

I will look upstream :(

**Comment by OniriCorpe** [comment]
Any news?

**Comment by xmgz** [comment]
It was an issue in some other servers, not only YNH, as we were talking in matrix room (at the date). As new media was corretly posted and displayed I did not follow the issue but it was atributted to database migration issues.

thank you (again)

**Comment by OniriCorpe** [comment]
So I can close this issue, thank you!
